# 数据库相关配置
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306
#    username: root
#    password: root

#demo:
#  key1: hello,yml
#  key2: key2
#  key3: ''


#student:
#  id: 18
#  name: zhangsan
#  age: 12
#
#dbtypes:
#  name:
#    - mysql
#    - sqlserver
#    - db2

#      file-name-pattern:

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/message?characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration: #配置打印MyBatis⽇志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #配置驼峰⾃动转换
