# 数据库相关配置
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306
#    username: root
#    password: root

#demo:
#  key1: hello,yml
#  key2: key2
#  key3: ''


#student:
#  id: 18
#  name: zhangsan
#  age: 12
#
#dbtypes:
#  name:
#    - mysql
#    - sqlserver
#    - db2

logging:
  file:
    name: logger/ioc.log
#    path: logger name优先级高于path

  logback:
    rollingpolicy:
      max-file-size: 200MB
#      file-name-pattern:
